### ISSUE TITLE
Plotting of pedigree names using plot.pedigree

### ISSUE THREAD

**Issue by Joemoe134** [mayoverse/kinship2#2]
Hello, i am trying to include a pedigree name at the top of the pedigree plots.
Is there no option to do so using plot.pedigree? I couldnt find anything in the documentation.

Cheers,
Jochen

**Comment by sinnweja** [comment]
I usually use the title function, like this:
R> library(kinship2)
R> example(pedigree)
R> plot(bped8, cex=.5)
R> title("pedigree number 8 from minnbreast")

**Comment by Joemoe134** [comment]
This of course works, thanks a lot for the prompt answer. 
I was stuck with trying to add this inside plot.pedigree().
Thank you!
