### ISSUE TITLE
Makekinship not a "bdsmatrix"

### ISSUE THREAD

**Issue by LouisLeNezet** [mayoverse/kinship2#22]
Hi,

In the example of makekinship, the matrix is said to be a "bdsmatrix" but is in fact when the example is ran a "dscmatrix".
Is it something wanted ?

```
data(minnbreast) 
table(minnbreast$sex)
length(unique(minnbreast$famid))

kin1 <- with(minnbreast,makekinship(famid, id, fatherid, motherid))
dim(kin1)

class(kin1)

# The next line shows that few of the elements of the full matrix are >0
length(kin1@blocks)/ prod(dim(kin1))
```

The consequence is that no parameter @blocks is available.

Louis

**Comment by sinnweja** [comment]
No, the bdsmatrix class was discontinued and we were encouraged to use dscmatrix classes.  I do not see the kin1@blocks test anywhere now, and it is fine to remove that line.
