### ISSUE TITLE
Broken pedigree

### ISSUE THREAD

**Issue by under-score** [mayoverse/kinship2#30]
I wonder why my multigenerational pedigree gets broken?

![Bildschirmfoto 2023-08-02 um 20 59 45](https://github.com/mayoverse/kinship2/assets/2796454/2ab3e153-940f-43c2-a524-300bf70cd7e8)

Should I change the order of ids?

**Comment by sinnweja** [comment]
Yes, re-ordering the ids does generally help the alignment. 
`peddf <- data.frame(id=1:14,
                  sex=c(1,2,1,2,1,2,1,1,2,1,2,1,1,2),
                  momid=c(NA,NA,2,14,4,9,6,NA,NA,NA,NA,NA,NA,NA),
                  dadid=c(NA,NA,1,13,3,8,5,NA,NA,NA,NA,NA,NA,NA))
ped <- with(peddf, pedigree(id=id, sex=sex, momid=momid, dadid=dadid))

par(mfrow=c(1,2))
plot(ped)
plot(ped[c(1:4,13,14,4:12)])`


![fixedped](https://github.com/mayoverse/kinship2/assets/8126016/fbbeea24-dd04-40c4-b200-6e9bd1345aaf)

**Comment by under-score** [comment]
Million thanks - maybe 
`plot(ped[c(1:4,13,14,5:12)])`
is even better ;-)

So the trick is to move the ancestors (13+14) of the "breaking" individual (4) before any individual in the next gen (5)? 

Spent several hours now with a N=200 pedigree but the results are unpredictable where even the whole plot is being messed up.
